export default {
  login: "darkquilius",
  id: 57682169,
  node_id: "MDQ6VXNlcjU3NjgyMTY5",
  avatar_url: "https://avatars1.githubusercontent.com/u/57682169?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/darkquilius",
  html_url: "https://github.com/darkquilius",
  followers_url: "https://api.github.com/users/darkquilius/followers",
  following_url: "https://api.github.com/users/darkquilius/following{/other_user}",
  gists_url: "https://api.github.com/users/darkquilius/gists{/gist_id}",
  starred_url: "https://api.github.com/users/darkquilius/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/darkquilius/subscriptions",
  organizations_url: "https://api.github.com/users/darkquilius/orgs",
  repos_url: "https://api.github.com/users/darkquilius/repos",
  events_url: "https://api.github.com/users/darkquilius/events{/privacy}",
  received_events_url: "https://api.github.com/users/darkquilius/received_events",
  type: "User",
  site_admin: false,
  name: "Andrew Reeves",
  company: null,
  blog: "",
  location: "Atlanta, GA",
  email: null,
  hireable: true,
  bio: "Full-stack developer and Georgia Tech grad. I am also an avid gamer and have a B.A. in political science from Georgia State as well.",
  twitter_username: null,
  public_repos: 27,
  public_gists: 0,
  followers: 11,
  following: 24,
  created_at: "2019-11-12T18:18:56Z",
  updated_at: "2020-12-16T15:49:17Z"
  }